// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: narwhal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetPort int32 `protobuf:"varint,1,opt,name=TargetPort,proto3" json:"TargetPort,omitempty"`
}

func (x *HBRequest) Reset() {
	*x = HBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HBRequest) ProtoMessage() {}

func (x *HBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HBRequest.ProtoReflect.Descriptor instead.
func (*HBRequest) Descriptor() ([]byte, []int) {
	return file_narwhal_proto_rawDescGZIP(), []int{0}
}

func (x *HBRequest) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

type HBReplay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *HBReplay) Reset() {
	*x = HBReplay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_narwhal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HBReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HBReplay) ProtoMessage() {}

func (x *HBReplay) ProtoReflect() protoreflect.Message {
	mi := &file_narwhal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HBReplay.ProtoReflect.Descriptor instead.
func (*HBReplay) Descriptor() ([]byte, []int) {
	return file_narwhal_proto_rawDescGZIP(), []int{1}
}

func (x *HBReplay) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_narwhal_proto protoreflect.FileDescriptor

var file_narwhal_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x09, 0x48, 0x42, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50,
	0x6f, 0x72, 0x74, 0x22, 0x1e, 0x0a, 0x08, 0x48, 0x42, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x32, 0x3b, 0x0a, 0x07, 0x4e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x12, 0x30,
	0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x42, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x00,
	0x42, 0x0f, 0x5a, 0x0d, 0x6e, 0x61, 0x72, 0x77, 0x68, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_narwhal_proto_rawDescOnce sync.Once
	file_narwhal_proto_rawDescData = file_narwhal_proto_rawDesc
)

func file_narwhal_proto_rawDescGZIP() []byte {
	file_narwhal_proto_rawDescOnce.Do(func() {
		file_narwhal_proto_rawDescData = protoimpl.X.CompressGZIP(file_narwhal_proto_rawDescData)
	})
	return file_narwhal_proto_rawDescData
}

var file_narwhal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_narwhal_proto_goTypes = []interface{}{
	(*HBRequest)(nil), // 0: proto.HBRequest
	(*HBReplay)(nil),  // 1: proto.HBReplay
}
var file_narwhal_proto_depIdxs = []int32{
	0, // 0: proto.Narwhal.HeartBeat:input_type -> proto.HBRequest
	1, // 1: proto.Narwhal.HeartBeat:output_type -> proto.HBReplay
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_narwhal_proto_init() }
func file_narwhal_proto_init() {
	if File_narwhal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_narwhal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_narwhal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HBReplay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_narwhal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_narwhal_proto_goTypes,
		DependencyIndexes: file_narwhal_proto_depIdxs,
		MessageInfos:      file_narwhal_proto_msgTypes,
	}.Build()
	File_narwhal_proto = out.File
	file_narwhal_proto_rawDesc = nil
	file_narwhal_proto_goTypes = nil
	file_narwhal_proto_depIdxs = nil
}
