// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: narwhal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NarwhalClient is the client API for Narwhal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NarwhalClient interface {
	HeartBeat(ctx context.Context, in *HBRequest, opts ...grpc.CallOption) (*HBReplay, error)
}

type narwhalClient struct {
	cc grpc.ClientConnInterface
}

func NewNarwhalClient(cc grpc.ClientConnInterface) NarwhalClient {
	return &narwhalClient{cc}
}

func (c *narwhalClient) HeartBeat(ctx context.Context, in *HBRequest, opts ...grpc.CallOption) (*HBReplay, error) {
	out := new(HBReplay)
	err := c.cc.Invoke(ctx, "/proto.Narwhal/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NarwhalServer is the server API for Narwhal service.
// All implementations must embed UnimplementedNarwhalServer
// for forward compatibility
type NarwhalServer interface {
	HeartBeat(context.Context, *HBRequest) (*HBReplay, error)
	mustEmbedUnimplementedNarwhalServer()
}

// UnimplementedNarwhalServer must be embedded to have forward compatible implementations.
type UnimplementedNarwhalServer struct {
}

func (UnimplementedNarwhalServer) HeartBeat(context.Context, *HBRequest) (*HBReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedNarwhalServer) mustEmbedUnimplementedNarwhalServer() {}

// UnsafeNarwhalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NarwhalServer will
// result in compilation errors.
type UnsafeNarwhalServer interface {
	mustEmbedUnimplementedNarwhalServer()
}

func RegisterNarwhalServer(s grpc.ServiceRegistrar, srv NarwhalServer) {
	s.RegisterService(&Narwhal_ServiceDesc, srv)
}

func _Narwhal_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NarwhalServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Narwhal/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NarwhalServer).HeartBeat(ctx, req.(*HBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Narwhal_ServiceDesc is the grpc.ServiceDesc for Narwhal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Narwhal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Narwhal",
	HandlerType: (*NarwhalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartBeat",
			Handler:    _Narwhal_HeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "narwhal.proto",
}
